### ISSUE TITLE
안녕하세요 혹시 요청종목도 받으시나요?

### ISSUE THREAD

**Issue by p7min** [QuantKang/QuantKang.github.io#1]
따로 비교 종목 요청도 받으시는지 궁금합니다.

따로 연락 가능한 방법이 없어서 깃허브로 연락드려요 

PDI HYT GOF 같은 채권형 펀드는 어떻게 수익률비교가 될지 궁금합니다.

**Comment by QuantKang** [comment]
자주 확인을 하지 않아서 답변이 늦었습니다.

일단 아래와 같은 채권 비교를 추가했습니다.

https://quantkang.github.io/vs/#%EB%AF%B8%EA%B5%AD-%EC%83%81%EC%9E%A5-%EC%B1%84%EA%B6%8C-etf

SHY와 IEF를 TLT와 비교한 경우입니다.

SHY vs TLT: https://quantkang.github.io/shy-vs-tlt/
IEF vs TLT: https://quantkang.github.io/ief-vs-tlt/

HYT, GOF, PDI를 SHY와 비교한 경우입니다.

HYT vs SHY: https://quantkang.github.io/hyt-vs-shy/
GOF vs SHY: https://quantkang.github.io/gof-vs-shy/
PDI vs SHY: https://quantkang.github.io/pdi-vs-shy/

SPY(S&P 500)과 비교한 경우입니다.

HYT vs SPY: https://quantkang.github.io/hyt-vs-spy/
GOF vs SPY: https://quantkang.github.io/gof-vs-spy/
PDI vs SPY: https://quantkang.github.io/pdi-vs-spy/


HYT가 제일 오래되었길래, HYT 기준으로 비교한 경우입니다.

GOF vs HYT: https://quantkang.github.io/gof-vs-hyt/
PDI vs HYT: https://quantkang.github.io/pdi-vs-hyt/

채권(폐쇄형 펀드 유형)쪽은 관심을 두지 않았서 몰랐는데, 기대 이상으로 좋아 보입니다. SPY보다 조금 못하긴 합니다만, 주식 ETF라고 해도 믿을 듯 합니다.

추가로 더 비교가 필요한 종목이 있으면, 알려주시면 가능한 반영하겠습니다.
