### ISSUE TITLE
안녕하세요 추가적인 종목요청입니다

### ISSUE THREAD

**Issue by p7min** [QuantKang/QuantKang.github.io#2]
대표적인 배당성장 친구들

schd 

dgro

dgrw

divo

4종목들이 궁금합니다

**Comment by QuantKang** [comment]
상장 기간이 가장 짧은 DIVO 기준으로 정리했습니다.

SCHD vs DIVO
https://quantkang.github.io/schd-vs-divo/

DGRO vs DIVO
https://quantkanga.github.io/dgro-vs-divo/

DGRW vs DIVO
https://quantkang.github.io/dgrw-vs-divo/


야후 파이낸스 데이터를 이용하는데, SCHD는 최근 액면 분할 후 지난 분배금이 보정되지 않은 듯 합니다. SCHD에 대한 데이터는 부정확합니다.

ETF CHECK의 데이터가 더 정확한 듯 합니다. 참고하세요.

SCHD vs DRGO vs DRGW vs DIVO
https://www.etfcheck.co.kr/mobile/etpitem/F00000MVE2/compare?compCode%5B%5D=F00000TNI5&compCode%5B%5D=F00000PMNI&compCode%5B%5D=F00000XH7M&directTab=0
